name: Automated Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install SSH key and configure known_hosts
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      # Step 3: Deploy application
      - name: Deploy application    
        env:
          HOST: ${{ secrets.EC2_IP }}
          USER: ${{ secrets.EC2_USER }}
          REPO_DIR: "/var/www/" # Adjust to where you want the code
        run: |
          ssh $USER@$HOST "
            echo 'Successfully connected!'
            mkdir -p $REPO_DIR
            chmod 700 $REPO_DIR
            touch $REPO_DIR/index.html
            echo 'Deployment complete.'
          "

      # Optional: Verify deployment (if applicable)
      # - name: Verify deployment
      #   run: ssh $USER@$HOST 'curl -I http://localhost'
