name: Deploy to Amazon EC2

on:
  push:
    branches: [main] # or your default branch

# env:
#   AWS_REGION: us-east-1 # or your preferred region

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

    #   - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_IP }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          echo "$KEY" > ssh_key.pem
          echo ssh_key.pem
            
        #   chmod 600 ssh_key.pem
        #   scp -i ssh_key.pem -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:~/app/
        #   ssh -i ssh_key.pem -o StrictHostKeyChecking=no ${USER}@${HOST} '
        #     cd ~/app
        #     # Add your deployment commands here, for example:
        #     # npm install
        #     # pm2 restart app
        #   '
