name: Deploy on AWS EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo Deployment Start
        run: echo "Deploying update to AWS EC2"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}                # Your EC2 instance's IP address
          username: ${{ secrets.EC2_USER }}           # The username to connect to EC2 (e.g., ubuntu, ec2-user)
          port: 22
          key: ${{ secrets.AWS_SSH_KEY }}             # Your private SSH key stored in GitHub Secrets
          script: |
            echo "Deploying to production server"
            
            # Define project directory and repository URL
            PROJECT_DIR="/var/www/"
            REPO_URL="https://github.com/benacton/reactjs-cicd-pipeline.git"

            # Check if project directory exists
            if [ -d "$PROJECT_DIR" ]; then
                echo "Directory exists. Pulling latest updates..."
                cd "$PROJECT_DIR"
                git pull origin main
            else
                echo "Directory does not exist. Cloning repository..."
                git clone "$REPO_URL" "$PROJECT_DIR"
                cd "$PROJECT_DIR"
            fi

            # Run deployment script after pulling or cloning
            # sudo chown -R deploy_user: .
            # sudo chown -R www-data: .

            echo "Deployment successfully completed!"

