name: Connect to AWS and print Hello World

on:
  push:
    branches:
      - main # You can change this to the branch where you want the action to run

jobs:
  connect-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Install SSH client
      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      # Step 3: Add the EC2 instance to known hosts (replace <EC2_IP>)
      - name: Add to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
        shell: bash

      # Step 4: SSH into the AWS server and print "Hello World" (replace <EC2_USER> and <EC2_IP>)
      - name: SSH into EC2 and print Hello World
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "echo Hello World from GitHub Actions"
        shell: bash
