name: Connect to AWS and print Hello World

on:
  push:
    branches:
      - main # You can change this to the branch where you want the action to run

jobs:
  connect-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Install SSH client
      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      # Step 2: Add the private SSH key to the ssh-agent
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      # Step 3: Add the EC2 instance to known hosts (replace <EC2_IP>)
      - name: Add to known hosts
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
        shell: bash

      # Step 4: SSH into the EC2 instance and print Hello World (replace <EC2_USER> and <EC2_IP>)
      - name: SSH into EC2 and print Hello World
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "echo Hello World from GitHub Actions"
        shell: bash
