name: Deploy on AWS EC2 Instance
# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - main

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init
        run: echo "Echo Deploying Update"
